name: Update README with GitHub Stats

on:
  push:
    branches:
      - test-workflow
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README.md
        run: |
          echo '<!-- Most Used Languages Centered -->' > README.md
          echo '<p align="center">' >> README.md
          echo '<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=sminerport&layout=compact&theme=default" alt="Top Languages" />' >> README.md
          echo '</p>' >> README.md

          echo '<!-- GitHub Stats Centered -->' >> README.md
          echo '<p align="center">' >> README.md
          echo '<img src="https://github-readme-stats.vercel.app/api?username=sminerport&show_icons=true&theme=default&count_private=true&token=${{ secrets.GH_TOKEN }}" alt="GitHub Stats" />' >> README.md
          echo '</p>' >> README.md

          echo '<!-- Trophies Centered -->' >> README.md
          echo '<p align="center">' >> README.md
          echo '<img src="https://github-profile-trophy.vercel.app/?username=sminerport&theme=flat&no-frame=true&margin-w=15" alt="Trophies" />' >> README.md
          echo '</p>' >> README.md

          echo '<!-- Snake Game Centered -->' >> README.md
          echo '<p align="center">' >> README.md
          echo '<img src="https://raw.githubusercontent.com/sminerport/snk/output/github-contribution-grid-snake.svg" alt="Snake Game" />' >> README.md
          echo '</p>' >> README.md
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README.md with stats and visuals"
          git push origin master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
