name: Auto-Update README with GitHub Stats and Visuals

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write # Allows writing to the repository, needed for pushing changes
  actions: read # Allows reading actions, which is needed for the workflow to execute

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make the script executable
        run: chmod +x ./scripts/update_readme.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run the update_readme.sh script
        run: ./scripts/update_readme.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update README.md with stats and visuals"
            git push origin master
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
